### PR TITLE
Add people's feed xml version.

### PR DESCRIPTION
**Pull request by hare1039**
Its hard-coded xml version. 
I can turn that into java version, but it will took more time

### CODE REVIEW

**Comment by jmgamer12** [comment]
Alright gonna try and change this to people/requests tabbed layout

**Comment by jmgamer12** [comment]
Also it's missing drawable/list

**Comment by hare1039** [comment]
OK
BTW, you can remove the java code if it does not compile
most of them doesn't effect the xml

**Comment by hare1039** [comment]
change `drawable/list` to any picture in the drawable folder

**Comment by jmgamer12** [comment]
Ok np

**Pull request merged**
