### PR TITLE
Add profile page

### PR DESCRIPTION
**Pull request by hare1039**
Hi
I wrote the profile page
Please tell me anything I can Improve

And I also change API level to 17, because my phone is only android 4.2

### CODE REVIEW

**Comment by jmgamer12** [comment]
Hey gonna leave the API at above 21 because it's not compatible with several things I've implemented. I recommend using the Nexus 5x virtual device or similar.

**Review by jmgamer12 — CHANGES_REQUESTED** [review]
Upgrade API level

**Comment by hare1039** [comment]
OK, I remove the commit
BTW, It look like this: 
screenshot_2018-11-28-00-14-24

**Comment by jmgamer12** [comment]
Ok np. Looks solid

**Comment by hare1039** [comment]
I forgot to add the user status string
so I add it here
https://github.com/hare1039/CS465-StudyBuddy/commit/7f30e663ef304ef913bd7fcd5b466057f15ebf75

**Pull request closed without merging**
